# Generated by Django 4.1.7 on 2023-02-27 13:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sobrenome', models.CharField(blank=True, max_length=150)),
                ('telefone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao', models.TextField(blank=True)),
                ('mostrar', models.BooleanField(default=True)),
                ('avatar', stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to='Avatars/%Y/%m/%d/', variations={'thumb': {'crop': True, 'height': 200, 'width': 200}})),
                ('do_user', models.IntegerField(default=None)),
                ('categoria', models.ForeignKey(choices=[('Família', 'Família'), ('Amigos', 'Amigos'), ('Escola', 'Escola'), ('Faculdade', 'Faculdade'), ('Curso', 'Curso'), ('Trabalho', 'Trabalho'), ('Academia', 'Academia'), ('Outros', 'Outros')], on_delete=django.db.models.deletion.DO_NOTHING, to='contatos.categoria')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['nome'],
            },
        ),
    ]
