# Generated by Django 4.1.7 on 2023-02-27 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_alter_contato_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='mostrar',
            new_name='publicada',
        ),
    ]
