# Generated by Django 4.1.7 on 2023-02-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0004_remove_contato_do_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
