# Generated by Django 4.1.7 on 2023-02-28 05:06

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0005_alter_contato_publicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='avatar',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='Avatars/%Y/%m/%d/', variations={'thumbnail': {'crop': True, 'height': 200, 'width': 200}}, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(max_length=11),
        ),
    ]
