# Generated by Django 4.1.7 on 2023-03-01 11:30

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0012_alter_contato_avatar_alter_contato_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='avatar',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='avatars/%Y/%m/%d/', variations={}, verbose_name='Avatar'),
        ),
    ]
