# Generated by Django 4.1.7 on 2023-03-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0014_contato_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='categoria',
            field=models.CharField(choices=[('Academia', 'Academia'), ('Amigos', 'Amigos'), ('Balada', 'Balada'), ('Clube', 'Clube'), ('Curso', 'Curso'), ('Escola', 'Escola'), ('Faculdade', 'Faculdade'), ('Família', 'Família'), ('Igreja', 'Igreja'), ('Outros', 'Outros'), ('Trabalho', 'Trabalho')], max_length=150),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
