# Generated by Django 4.1.7 on 2023-03-03 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('usuario', models.CharField(max_length=150)),
                ('senha', models.CharField(max_length=150)),
                ('senha2', models.CharField(max_length=150)),
            ],
        ),
    ]
